---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/common
resources:
  # Networking
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  # Storage
  - ./csi-driver-nfs/ks.yaml
  # Hardware
  - ./intel-device-plugin-operator/ks.yaml
  # Utilities
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
