# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: n8n-secret
stringData:
  #ENC[AES256_GCM,data:dDMb/v1FpE/P8g682YJFZi6oXOfS8KraZLOgUBAM7rfWyf/Eb8tmQLq47VKJoWWZ2A==,iv:h+U+2cVyj24U0VhenKnpZaCAFbU05UXjE8ULJTvxpQs=,tag:MxaWyB4MJZCb0dBXeBp0Bg==,type:comment]
  #ENC[AES256_GCM,data:O5wjzgB1Ps1KTr5RYWebjZGHaAo8u3HmAg8ykG995ZzT//Cg5u7wSxgfQ8mHB32V3aeN9g==,iv:utN4mhdcYbNXL6sLsHHM9bErTE/iAn8ElLh7FR9LjF4=,tag:Yr2Y+M9QO/FU3qXQ51+ihg==,type:comment]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:ml4TU8BqZrnr0HSDXuJkKLqo6A+YiHPJTShXFKT0BxapO3Mj070a3wBNQPU=,iv:98ySvHKiDvNaAmj4SXT6shyObkqjllIwW2POKI7cWDo=,tag:QSZWDJ8DAijgD9kX0UfeoA==,type:str]
sops:
  age:
    - recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLenlpTEgzOEY2aVVpdUI3
        d1M0a0RRditPbkJLVEk2OCtTVWIwdyttR1FnCk80K1ZRRTNqeTdLbzlPUEZBZXNw
        a2pWT3Y0Y3EvaE5KUTVuL1NzbVA4bjgKLS0tIGY2c05aWGtNVno4ZlFHSUxBczRF
        eHFLa2hsaFBwS3BuTlBJb1kxWFozMFkKqzqw5XAWhNakEINscttAdlfLqZlGn4mx
        jEtKYqLD2oGImrNrEMDuMahjHUzRDm4E2oEsykfejEqv4oV4uhq67g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T14:12:44Z"
  mac: ENC[AES256_GCM,data:KHVad5YsBkjfrboNfBiC6sK5y+dsWluDMBdSzzOpMlXZBKogqQhADXV1j4+fdBI/Z80Bm7B907ES+kJmic28o7XjpZa3HdV8gD/CPwF/APNMgz30wWpTvwUp2g8aMaG+y26b+vzS/wSMLvxqTf/OzgG+HCsMZlClnGxNKfz5fHo=,iv:2BwKRob7Yym4IT61yGv17vDeaRcTP/2qv86Rc9h6PM0=,tag:cC2MYsfXcaYUeLyF1M/qOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
