apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: observability
spec:
  template:
    spec:
      containers:
      - name: loki-sc-rules
        env:
        - name: TMPDIR
          value: /rules
        - name: TEMP
          value: /rules
        - name: TMP
          value: /rules