---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: proxmox
  namespace: default
spec:
  endpoints:
    - dnsName: "proxmox.k8s.merox.dev"
      recordType: A
      targets: ["10.57.57.254"]
