---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: default
subsets:
  - addresses:
      - ip: 10.57.57.254
    ports:
      - port: 8006
        protocol: TCP
        name: https
